package com.clone.pastebin;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;
import java.time.LocalDate;

@Controller // This means that this class is a Controller
@RequestMapping(path="/paste") // This means URL's start with /paste (after Application path)
public class MainController {
    @Autowired // This means to get the bean called PastebinRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PastebinRepository pastebinRepository;

    @GetMapping("/add")
    public String pastebinForm(Model model) {
        model.addAttribute("paste", new Pastebin());
        return "add";
    }

    @PostMapping("/id")
    public String pastebinSubmit(@ModelAttribute Pastebin pastebin, Model model) {
        model.addAttribute("pastebinResult", pastebin);
        LocalDate date = LocalDate.now();
        pastebin.setPasteDate(date);
        pastebinRepository.save(pastebin);
        return "id";
    }

    @GetMapping(path="/list")
    public String getAllPaste(Model model) {
        model.addAttribute("pasteBin", pastebinRepository.findAll());
        return "list";
    }

    @GetMapping("/accessPaste")
    public String getIdPaste(@PathVariable("id") long id, Model model) {
        Pastebin pastebin = pastebinRepository.findById((int) id)
                .orElseThrow(() -> new IllegalArgumentException("Invalid user Id:" + id));

        model.addAttribute("pasteBin", pastebin);
        return "accessPaste";
    }

}
