package com.clone.pastebin;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;

import static java.util.Calendar.getInstance;

@Controller // This means that this class is a Controller
//@RequestMapping() // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called PastebinRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PastebinRepository pastebinRepository;

    @GetMapping("/pastebinEndpoint")
    public String pastebinForm(Model model) {
        model.addAttribute("paste", new Pastebin());
        return "pastebinForm";
    }

    @PostMapping("/pastebinEndpoint")
    public String pastebinSubmit(@ModelAttribute Pastebin pastebin, Model model) {
        model.addAttribute("pastebinResult", pastebin);
        LocalDate date = LocalDate.now();
        pastebin.setPasteDate(date);
        pastebinRepository.save(pastebin);
        return "result";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Pastebin> getAllPaste() {
        // This returns a JSON or XML with the pastes
        return pastebinRepository.findAll();
    }
}
